# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-01 12:07
from __future__ import unicode_literals

import beers.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name=b'Created at')),
                ('last_modified_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name=b'Last modified at')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('abv', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Alcohol by volume')),
                ('is_filtered', models.BooleanField(default=False, verbose_name='Is filtered?')),
                ('color', models.PositiveSmallIntegerField(choices=[(1, 'yellow'), (2, 'amber'), (3, 'brown'), (4, 'black')], default=1, verbose_name='Color')),
                ('image', models.ImageField(blank=True, null=True, upload_to=beers.models.image_upload_location, verbose_name='Image')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Beer',
                'verbose_name_plural': 'Beers',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name=b'Created at')),
                ('last_modified_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name=b'Last modified at')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beers_company_created', to=settings.AUTH_USER_MODEL, verbose_name=b'Created by')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beers_company_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name=b'Last modified by')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='SpecialIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name=b'Created at')),
                ('last_modified_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name=b'Last modified at')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('beers', models.ManyToManyField(blank=True, related_name='special_ingredients', to='beers.Beer')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beers_specialingredient_created', to=settings.AUTH_USER_MODEL, verbose_name=b'Created by')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beers_specialingredient_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name=b'Last modified by')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Special ingredient',
                'verbose_name_plural': 'Special ingredients',
            },
        ),
        migrations.AddField(
            model_name='beer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beers', to='beers.Company'),
        ),
        migrations.AddField(
            model_name='beer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beers_beer_created', to=settings.AUTH_USER_MODEL, verbose_name=b'Created by'),
        ),
        migrations.AddField(
            model_name='beer',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beers_beer_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name=b'Last modified by'),
        ),
    ]
