# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-01 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0002_company_tax_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='tax_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tax number'),
        ),
    ]
